on:
  push:
    brnaches:
      - main
jobs:
  install-build-module:
    runs-on: windows-11-arm
    steps: 
    - name: Checkout Source Code
      uses: actions/checkout@v4  
    - name: "Installing Build Module"
      run: Install-Module -Name "ModuleBuilder" -Scope CurrentUser -Force -AcceptLicense
    - name: Compile Module Files
      run: Build-Module -Path Source
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-powershell-module  
        path: .\Output\ModuleBuilder\0.0.0\ModuleBuilder.psd1